# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b9fb51f3c27908ef6a3b025f218404410d16d82b7c6252c573ec3628b2b552c8d2c1c2c4ec14c671a86135d95cf051fe9c4fbf734d568cfc35009240fa894dc

test:
  secret_key_base: 3cd389aaed793c9e20aea969ff2bf0078bd8b0085b9cfab3ae910a87b8ab7db757ae9063681a50c469519d60575a04d0e260a9329ecb18fa0a641a2aed1927a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
